<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="03020MP" ignored="0" name="Suite de tests" tests="4" failures="1" timestamp="17 dÃ©c. 2019 13:33:02 GMT" time="0.318" errors="0">
  <testcase name="test_B_1" time="0.021" classname="acial.selenium.exercices.testB"/>
  <testcase name="test_B_2" time="0.019" classname="acial.selenium.exercices.testB"/>
  <testcase name="test_A_2" time="0.011" classname="acial.selenium.exercices.testA"/>
  <testcase name="test_A_1" time="0.03" classname="acial.selenium.exercices.testA">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at acial.selenium.exercices.testA.test_A_1(testA.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test_A_1 -->
</testsuite> <!-- Suite de tests -->
